print("======= Data diri mahasiswa =======")
nim = input("NIM          : ")
nama = input("Nama lengkap : ")
jurusan = input("Jurusan      : ")
alamat = input("Alamat       : ")
print("Hasil cetak data di atas")
print(f"Nim          : {nim}")
print(f"Nama         : {nama}")
print(f"jurusan      : {jurusan}")
print(f"Alamat       : {alamat}")